function read(){
    
    document.getElementById("para1").style.display ="block";
}

function change(){
    document.getElementById("para1").innerHTML = "Natural lakes are generally found in mountainous areas (i.e. alpine lakes), dormant volcanic craters, rift zones and areas with ongoing glaciation. Other lakes are found in depressed landforms or along the courses of mature rivers, where a river channel has widened over a basin formed by eroded floodplains and wetlands. Some parts of the world have many lakes formed by the chaotic drainage patterns left over from the last ice age. All lakes are temporary over long periods of time, as they will slowly fill in with sediments or spill out of the basin containing them.Artificially controlled lakes are known as reservoirs, and are usually constructed for industrial or agricultural use, for hydroelectric power generation, for supplying domestic drinking water, for ecological or recreational purposes, or for other human activities.";
    document.getElementById("para").innerHTML = "A lake is a naturally occurring, relatively large and fixed body of water on the Earth's surface. It is localized in a basin or interconnected basins surrounded by dry land.[1] Lakes lie completely on land and are separate from the ocean, although they may be connected with the ocean by rivers, such as Lake Ontario. Most lakes are freshwater and account for almost all the world's surface freshwater, but some are salt lakes with salinities even higher than that of seawater. Lakes vary significantly in surface area and volume Lakes are typically larger and deeper than ponds, which are also water-filled basins on land, although there are no official definitions or scientific criteria distinguishing the two.[2] Lakes are also distinct from lagoons, which are shallow tidal pools dammed by sandbars at coastal regions of oceans or large lakes. Most lakes are fed by springs, and both fed and drained by creeks and rivers, but some lakes are endorheic without any outflow, while volcanic lakes are filled directly by precipitation runoffs and do not have any inflow streams"
    document.querySelecto('img[src=["https://images.unsplash.com/photo-1541344436227-8c914512d905?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fHBlcnNvbiUyMG91dHNpZGV8ZW58MHx8MHx8fDA%3D"]').src = "https://media.istockphoto.com/id/944987728/photo/a-pair-of-lovers-sits-on-the-bridge.jpg?s=612x612&w=0&k=20&c=zi9Pu4E6OKv7pYuPtP54GopGBApgLL1ytfaQSm06LBE=";
}
function change1(){
    document.getElementById("para1").innerHTML ="Nature is the source of all essential nutrients for all living things on the planet, including humans. Humans are part of nature and not separate from it. We go through great expense and trouble to leave our cities and put ourselves into natural environments where we can enjoy these beautiful places.Nature photography is as much a physical exercise as it is the exercise for the soul. By staying close to nature, we feel more grateful and appreciative of what it has to offer to us. We should take full advantage of the nature and go out of home for the morning walk daily to breathe pure air and enjoy morning beauty of nature.";
    document.getElementById("para").innerHTML = "Nature is the source of all essential nutrients for all living things on the planet, including humans. Humans are part of nature and not separate from it. We go through great expense and trouble to leave our cities and put ourselves into natural environments where we can enjoy these beautiful places. Nature photography brings individuals close to nature and away to the high toxicity of the cities, thus restoring to an extent the physical health. Nature photography is as much a physical exercise as it is the exercise for the soul. Those who are away from nature can't understand the beauty that is held by Nature. The rise in population on planet earth is leading to a rise in consumption of natural resources.";
}